### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by javatlacati** [Jbranadev/JBSqlUtils#1]
Mi compa ha considerado subir su proyecto a maven central?

**Comment by javatlacati** [comment]
`[![Maven Central](https://img.shields.io/maven-central/v/com.github.javatlacati/contiperf.svg?label=Maven%20Central)](https://search.maven.org/search?q=g:%22com.github.javatlacati%22%20AND%20a:%22contiperf%22)`

**Comment by Jbranadev** [comment]
Se añadieron las etiquetas correspondientes a la Licencia y en la sección inferior del Readme.md, se encuentra como obtener la compilación del proyecto a través de Maven o Gradle. 

![image](https://github.com/Jbranadev/JBSqlUtils/assets/117953364/a50fd603-8c0a-4855-8046-6c42edb7107f)

Adicional se incluye el enlace hacía Maven central donde se brinda la opción de obtener una compilación por los diferentes manejadores de paquetes que posee.

![image](https://github.com/Jbranadev/JBSqlUtils/assets/117953364/fb102e07-70e1-44e9-848c-208cc5b24124)
