### ISSUE TITLE
Crear release.

### ISSUE THREAD

**Issue by javatlacati** [Jbranadev/JBSqlUtils#3]
Hay gente que por alguna razón no puede o no quiere usar maven central. Crear releases permite consumir el repo mediante jitpack o descargar una versión estable del proyecto más fácilmente.

**Comment by Jbranadev** [comment]
Un gusto saludarte, gracias por la sugerencia, me permitió investigar y aprender a cerca de JitPack y las versiones raleases en GitHub.

Ya puedes utilizar JitPack para obtener una compilación del proyecto.

![Uploading image.png…]()
